services:
    netbull_hashids.hashids:
        class: 'Hashids\Hashids'
        arguments: ["%netbull_hashids.salt%", "%netbull_hashids.min_hash_length%", "%netbull_hashids.alphabet%"]
        public: true

    NetBull\HashidsBundle\Request\ParamConverter\HashParamConverter:
        arguments: ['@netbull_hashids.hashids']
        tags: [{ name: request.param_converter, priority: 2, converter: hash }]

    netbull_hashids.twig.hashids_extension:
        class: 'NetBull\HashidsBundle\Twig\HashidsExtension'
        arguments: ['@netbull_hashids.hashids']
        tags: [{ name: twig.extension }]
