services:
    Hashids\Hashids:
        arguments: [ "%netbull_hashids.salt%", "%netbull_hashids.min_hash_length%", "%netbull_hashids.alphabet%" ]
        public: true

    NetBull\HashidsBundle\Twig\HashidsExtension:
        arguments: [ '@Hashids\Hashids' ]
        tags:
            - twig.extension

    NetBull\HashidsBundle\ArgumentResolver\HashValueResolver:
        arguments: [ '@Hashids\Hashids', '%netbull_hashids.min_hash_length%' ]
        tags:
            - controller.argument_value_resolver:
                  name: NetBull\HashidsBundle\ArgumentResolver\HashValueResolver
                  priority: 150
