services:
    netbull_hashids.hashids:
        class: 'Hashids\Hashids'
        arguments: ["%netbull_hashids.salt%", "%netbull_hashids.min_hash_length%", "%netbull_hashids.alphabet%"]
        public: true

    Hashids\Hashids:
        alias: 'netbull_hashids.hashids'

    netbull_hashids.twig.hashids_extension:
        class: 'NetBull\HashidsBundle\Twig\HashidsExtension'
        arguments: ['@netbull_hashids.hashids']
        tags: [{ name: twig.extension }]

    NetBull\HashidsBundle\ArgumentResolver\HashValueResolver:
        tags:
            - controller.argument_value_resolver:
                  name: hashid
                  priority: 150
